---
nodeLinker: node-modules

packageExtensions:
  docusaurus-theme-redoc@*:
    peerDependencies:
      webpack: '*'
  redoc@*:
    dependencies:
      call-me-maybe: '*'
      fast-safe-stringify: '*'
      yaml: '*'
  styled-components@*:
    dependencies:
      react-is: '*'

yarnPath: .yarn/releases/yarn-3.3.1.cjs
