/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  autogeneratedSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], // TODO: remove me once references user-docs are fixed
};

module.exports = sidebars;
