# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

---
build:bookworm:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - >
      if [ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]; then
        export KANIKO_EXTRA_ARGS="--no-push"
      fi
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/images/bookworm/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR-bookworm
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR.$RUST_MINOR-bookworm
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR.$RUST_MINOR.$RUST_PATCH-bookworm
      --destination $CI_REGISTRY_IMAGE:bookworm
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR.$RUST_MINOR
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR.$RUST_MINOR.$RUST_PATCH
      --destination $CI_REGISTRY_IMAGE:latest
      --build-arg RUST_VERSION=$RUST_VERSION
      --force
      $KANIKO_EXTRA_ARGS

build:bookworm-slim:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - >
      if [ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]; then
        export KANIKO_EXTRA_ARGS="--no-push"
      fi
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/images/bookworm/slim/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR-slim-bookworm
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR.$RUST_MINOR-slim-bookworm
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR.$RUST_MINOR.$RUST_PATCH-slim-bookworm
      --destination $CI_REGISTRY_IMAGE:slim-bookworm
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR-slim
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR.$RUST_MINOR-slim
      --destination $CI_REGISTRY_IMAGE:$RUST_MAJOR.$RUST_MINOR.$RUST_PATCH-slim
      --destination $CI_REGISTRY_IMAGE:slim
      --build-arg RUST_VERSION=$RUST_VERSION
      --force
      $KANIKO_EXTRA_ARGS
