---
stages:
  - lint
  - build

lint:yaml:
  image: alpine
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

build:container:
  variables:
    IMAGE_DESTIANTION_ARGS: --no-push
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        IMAGE_DESTIANTION_ARGS: --destination $CI_REGISTRY_IMAGE:dev
    - if: $CI_COMMIT_TAG != null
      variables:
        IMAGE_DESTIANTION_ARGS: >
          --destination $CI_REGISTRY_IMAGE:latest
          --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - if: >
        $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH &&
        $CI_COMMIT_BRANCH != null
      variables:
        IMAGE_DESTIANTION_ARGS: --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      $IMAGE_DESTIANTION_ARGS
      --force
