#!/bin/bash

set -xe

SCRIPT_DIR=$(dirname "$0")
# shellcheck source=ci/include/clone.sh
. "$SCRIPT_DIR"/include/clone.sh
REPO_NAME=${REPO_NAME_SMTP_MAILER:-opentalk/backend/services/smtp-mailer}
REPO_BRANCH=${REPO_BRANCH_SMTP_MAILER:-main}

clone_repo "$REPO_NAME" "$REPO_BRANCH"

mkdir -p admin-docs/smtp-mailer 

deploy_to admin-docs/smtp-mailer ".tmp/$REPO_NAME/docs/admin/*"
