# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "smtp-mailer"
version = "0.0.0-dev"
edition = "2021"
publish = false
description = "Mail Worker that takes mail send tasks from a queue, renders them, and sends them out via SMTP"
build = "build.rs"

[dependencies]
# mail-worker-proto = { git = "https://git.heinlein-video.de/heinlein-video/k3k-controller", package = "mail-worker-proto"  }
# mail-worker-proto = { git = "ssh://git@git.heinlein-video.de:222/r.floren/k3k-controller.git", version = "0.1.0", branch = "mails", package = "mail-worker-proto" }
mail-worker-protocol = { path = "vendored/k3k-controller/crates/mail-worker-protocol", package = "opentalk-mail-worker-protocol" }
types = { path = "vendored/k3k-controller/crates/types", package = "opentalk-types" }

# ics-chrono-tz = { git = "ssh://git@git.heinlein-video.de:222/k.baltruschat/ics-timezones.git", branch = "main" }
ics-chrono-tz = { path = "vendored/ics-chrono-tz" }

lapin = { version = "2.1.1", default-features = false }
tokio-reactor-trait = "1"
tokio-executor-trait = "2"
tokio = { version = "1.18.2", default-features = false, features = [
  "signal",
  "macros",
  "rt-multi-thread",
] }

clap = { version = "3.1.18", features = ["derive"] }
config = { version = "0.13.1", default-features = false, features = ["toml"] }
log = "0.4.17"
env_logger = "0.9.0"

anyhow = "1.0.57"
thiserror = "1.0.31"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.6" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_path_to_error = "0.1.4"
async-trait = "0.1.53"
url = { version = "2.2.2", features = ["serde"] }
futures = "0.3.21"
bytes = "1.1.0"
uuid = { version = "1.0.0", features = ["serde", "v4"] }

percent-encoding = "2.1"
tera = { version = "1.15.0", features = ["builtins"] }
fluent-templates = { version = "0.7.1", features = ["tera"] }
phonenumber = "0.3"

lettre = { version = "0.10.0", default-features = false, features = [
  "builder",
  "hostname",
  "smtp-transport",
  "tokio1-rustls-tls",
  "tokio1",
] }
css-inline = { version = "0.10.5" }

ics = { version = "0.5" }
textwrap = "0.16.0"

[dev-dependencies]
pretty_assertions = "1.2.1"


[build-dependencies]
vergen = "7.2.1"
anyhow = "1.0"
